---
blokli_url: https://blokli.prod.hoprnet.link
db:
  data: /var/lib/hoprd
identity:
  file: "/etc/hoprd/hopr.id"
  password: "change_me"
api:
  enable: true
strategy:
  allow_recursive: false
  strategies:
    - AutoRedeeming:
        redeem_all_on_close: true
    - ChannelLifecycle:
        population:
          min_open_channels: 5
          target_open_channels: 20
        funding:
          initial_capacity: "1 GiB"
          topup_capacity: "512 MiB"
          lower_capacity_threshold: "512 MiB"
        finalizer:
          finalize_max_concurrent: 5
        concurrency:
          max_concurrent_actions: 5
hopr:
  safe_module:
    safe_address: "0x0000000000000000000000000000000000000000" # NOTE: fill in value
    module_address: "0x0000000000000000000000000000000000000000" # NOTE: fill in value
