---
# FIXME: The nodes can't dial each other within the docker container. 
services:
  chain:
    container_name: hoprd-blokli-anvil
    platform: linux/amd64
    image: europe-west3-docker.pkg.dev/hoprassociation/docker-images/bloklid-anvil:0.10.5-pr.349@sha256:2e6747d9d6c97255474e243b5088d131f01bb67b5d8f17dbac6bb8aafdf1d7b6
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
  cluster:
    container_name: hoprd-localcluster
    platform: linux/amd64
    image: hoprd-localcluster:latest
    depends_on:
      chain:
        condition: service_healthy
    environment:
      HOPRD_CHAIN_URL: http://chain:8080
      RUST_LOG: debug
    command:
      - --size
      - "${CLUSTER_SIZE:-3}"
      - --api-port-base
      - "3001"
      - --p2p-port-base
      - "9001"
    ports:
      - "3001-300${CLUSTER_SIZE:-3}:3001-300${CLUSTER_SIZE:-3}"
