---
################################################################################
# Pipeline to run on merge to main / release branches
################################################################################
name: Merge
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - "release/*"
concurrency:
  group: merge-${{ github.event.pull_request.base.ref }}
  cancel-in-progress: false
permissions:
  contents: read
jobs:
  build-binaries:
    name: Binary ${{ matrix.binary }} ${{ matrix.architecture }}
    if: github.event.pull_request.merged == true
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64-linux
            runner: depot-ubuntu-24.04-8
            build_command: nix build -L .#binary-hoprd-x86_64-linux
            build_file: ./hoprd/Cargo.toml
            binary: hoprd
          - architecture: aarch64-linux
            runner: depot-ubuntu-24.04-arm-8
            build_command: nix build -L .#binary-hoprd-aarch64-linux
            build_file: ./hoprd/Cargo.toml
            binary: hoprd
          - architecture: x86_64-linux
            runner: depot-ubuntu-24.04-8
            build_command: nix build -L .#binary-hoprd-localcluster-x86_64-linux
            build_file: ./localcluster/Cargo.toml
            binary: hoprd-localcluster
    uses: hoprnet/hopr-workflows/.github/workflows/build-binaries.yaml@eedb4b7701714299852ca5243f1544b817653f33 # 0.11.1
    permissions:
      contents: read
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.merge_commit_sha }}
      version_type: pr
      architecture: ${{ matrix.architecture }}
      build_file: ${{ matrix.build_file }}
      build_command: ${{ matrix.build_command }}
      binary: ${{ matrix.binary }}
      runner: ${{ matrix.runner }}
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_HOPRNET_PRIVATE_KEY }}
  build-docker:
    name: Docker
    needs: build-binaries
    if: github.event.pull_request.merged == true
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker.yaml@eedb4b7701714299852ca5243f1544b817653f33 # 0.11.1
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.merge_commit_sha }}
      version_type: pr
      build_matrix: >-
        [
          {
            "runner": "depot-ubuntu-24.04-4",
            "architecture": "x86_64-linux",
            "build_command": "nix build -L .#docker-hoprd-x86_64-linux"
          },
          {
            "runner": "depot-ubuntu-24.04-4",
            "architecture": "aarch64-linux",
            "build_command": "nix build -L .#docker-hoprd-aarch64-linux"
          }
        ]
      build_file: ./hoprd/Cargo.toml
      docker_image_name: hoprd
      docker_image_format: skopeo
      fail_on_scan_vulnerabilities: ${{ vars.FAIL_ON_SCAN_VULNERABILITIES }}
      deployment_namespace: core-team
      deployment_label_selector: app.kubernetes.io/component=node
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  deploy-dev:
    name: Deploy Gnosis Dev
    runs-on: depot-ubuntu-24.04
    needs: build-docker
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Deploy to Gnosis Dev
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.GNOSIS_GITHUB_WORKFLOW_TOKEN }}
          repository: gnosis/gnosis_vpn-infrastructure
          event-type: restart_hoprd
          client-payload: |-
            {
              "environment": "dev"
            }
  cache_deps:
    name: Cache deps
    if: github.event.pull_request.merged == true
    runs-on: depot-ubuntu-24.04-4
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Cache dependencies
        uses: hoprnet/hopr-workflows/actions/nix-action@c2aca7e56d25c4a786049ccf816c7f1af8721de8 # nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.merge_commit_sha }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: |
            set -e
            cat >> .cargo/config.toml << TOML
            [source.hopr-cargo-registry-cache]
            registry = "sparse+${PRIVATE_CARGO_REGISTRY_PROXY_URL}"

            [source.crates-io]
            replace-with = "hopr-cargo-registry-cache"
            TOML
            nix develop -c cargo fetch
        env:
          PRIVATE_CARGO_REGISTRY_PROXY_URL: ${{ secrets.PRIVATE_CARGO_REGISTRY_PROXY_URL }}
  docs:
    name: Docs
    if: github.event.pull_request.merged == true
    needs:
      - build-docker
    runs-on: depot-ubuntu-24.04-4
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - name: Build docs
        uses: hoprnet/hopr-workflows/actions/nix-action@c2aca7e56d25c4a786049ccf816c7f1af8721de8 # nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.merge_commit_sha }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: |
            set -e
            RUSTDOCFLAGS="-D warnings" nix develop -c cargo doc --no-deps --document-private-items --no-default-features --features runtime-tokio,telemetry,transport-quic
            nix build -L .#docs
      - name: Increase git buffer size
        run: git config --global http.postBuffer 524288000
      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/share/doc/
          force_orphan: true
  notify:
    name: Notify failure
    needs:
      - build-binaries
      - build-docker
      - deploy-dev
      - docs
    if: ${{ always() && github.event.pull_request.merged == true && !success() }}
    runs-on: depot-ubuntu-24.04
    steps:
      - name: Notify failed merge pipeline
        uses: zulip/github-actions-zulip/send-message@f675f2b4eb2a95fae974215476dcb7ad8dfeff6b # v2.0.2
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ secrets.ZULIP_EMAIL }}
          organization-url: "https://hopr.zulipchat.com"
          type: "stream"
          to: "HOPRd"
          topic: "Core"
          content: |
            The merge pipeline has failed for pull request [#${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
  cleanup_actions:
    name: Cleanup Actions
    if: github.event.pull_request.merged == true
    runs-on: depot-ubuntu-24.04
    permissions:
      actions: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}
          BRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"

          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R "$REPO" -B "$BRANCH" | cut -f 1 )

          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
            gh actions-cache delete "$cacheKey" -R "$REPO" -B "$BRANCH" --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
