---
################################################################################
# Pull request pipeline for hoprd
################################################################################
name: PR
on:
  merge_group:
    types: [checks_requested]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
permissions:
  contents: read
  id-token: write # zizmor: ignore[excessive-permissions]
concurrency:
  group: ${{ github.event.pull_request.head.ref || github.ref_name }}-pr
  cancel-in-progress: true
jobs:
  validate-pr-title:
    name: Validate title
    if: github.event_name == 'pull_request'
    runs-on: depot-ubuntu-24.04
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            build
            chore
            docs
            style
            refactor
            perf
            test
          requireScope: false
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
  label:
    name: Add labels
    if: github.event_name == 'pull_request'
    runs-on: depot-ubuntu-24.04
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/labeler@77a4082b841706ac431479b7e2bb11216ffef250 # main on 20.02.2025
        with:
          sync-labels: true
      - name: Add "external" label for forked PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_REPO: ${{ github.repository }}
          HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [[ "$HEAD_REPO" != "$BASE_REPO" ]]; then
            gh pr edit "$PR_NUMBER" --add-label "external"
          fi
  checks:
    name: Check
    uses: hoprnet/hopr-workflows/.github/workflows/checks.yaml@d0cffaf9e9209c8eca00e8c74e82ac3f5f3cf7bb # workflow-checks-v2
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      runner_small: depot-ubuntu-24.04
      runner_large: depot-ubuntu-24.04-4
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  tests:
    name: Test
    uses: hoprnet/hopr-workflows/.github/workflows/tests.yaml@798d791de5c5485c3043049781dfd0938539a36a # workflow-tests-v6
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      enable_unit_tests: true
      enable_integration_tests: false
      enable_nightly_tests: true
      enable_benchmarks: false
      enable_unit_coverage: true
      enable_integration_coverage: false
      unit_coverage_command: |
        nix build -L .#coverage-unit
        cp result coverage.lcov
      runner_unit: depot-ubuntu-24.04-16
      runner_integration: depot-ubuntu-24.04-8
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  build-binaries:
    name: Binary ${{ matrix.binary }} ${{ matrix.architecture }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64-linux
            runner: depot-ubuntu-24.04-8
            build_command: nix build -L .#binary-hoprd-x86_64-linux
            build_file: ./hoprd/Cargo.toml
            binary: hoprd
            required_label: ""
          - architecture: aarch64-linux
            runner: depot-ubuntu-24.04-arm-8
            build_command: nix build -L .#binary-hoprd-aarch64-linux
            build_file: ./hoprd/Cargo.toml
            binary: hoprd
            required_label: "binary:aarch64-linux"
          - architecture: aarch64-darwin
            runner: depot-macos-15
            build_command: nix build -L .#binary-hoprd-aarch64-darwin
            build_file: ./hoprd/Cargo.toml
            binary: hoprd
            required_label: binary:aarch64-darwin
          - architecture: x86_64-darwin
            runner: depot-macos-15
            build_command: nix build -L .#binary-hoprd-x86_64-darwin
            build_file: ./hoprd/Cargo.toml
            binary: hoprd
            required_label: binary:x86_64-darwin
          - architecture: x86_64-linux
            runner: depot-ubuntu-24.04-8
            build_command: nix build -L .#binary-hoprd-localcluster-x86_64-linux
            build_file: ./localcluster/Cargo.toml
            binary: hoprd-localcluster
            required_label: ""
    uses: hoprnet/hopr-workflows/.github/workflows/build-binaries.yaml@fd29bf3c58b72faacc300e068a05b59eb3b180bc # 0.10.1
    permissions:
      contents: read
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: commit
      architecture: ${{ matrix.architecture }}
      build_file: ${{ matrix.build_file }}
      build_command: ${{ matrix.build_command }}
      binary: ${{ matrix.binary }}
      runner: ${{ matrix.runner }}
      enabled: ${{ matrix.required_label == '' || contains(github.event.pull_request.labels.*.name, matrix.required_label) }}
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_HOPRNET_PRIVATE_KEY }}
  build-docker:
    name: Docker
    needs: build-binaries
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker.yaml@fa71078959cf9f892185e8df16551720693a2cd1 # 0.9.3
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: commit
      build_matrix: >-
        [
          {
            "runner": "depot-ubuntu-24.04-4",
            "architecture": "x86_64-linux",
            "build_command": "nix build -L .#docker-hoprd-profile-x86_64-linux",
            "build_debug_command": "nix build -L .#docker-hoprd-dev-x86_64-linux"
          }
        ]
      build_file: ./hoprd/Cargo.toml
      docker_image_name: hoprd
      docker_image_format: skopeo
      deployment_namespace: core-team
      deployment_label_selector: app.kubernetes.io/component=node
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  docs:
    name: Docs
    runs-on: depot-ubuntu-24.04-4
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Build docs
        uses: hoprnet/hopr-workflows/actions/nix-action@c2aca7e56d25c4a786049ccf816c7f1af8721de8 # nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: |
            set -e
            RUSTDOCFLAGS="-D warnings" nix develop -c cargo doc --no-deps --document-private-items --no-default-features --features runtime-tokio,telemetry,transport-quic
            nix build -L .#docs
