---
name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Version type after release
        required: true
        type: choice
        default: "patch"
        options:
          - rc
          - patch
          - minor
          - major
concurrency:
  group: release
  cancel-in-progress: false
permissions:
  contents: read
jobs:
  build-binaries:
    name: Binary ${{ matrix.architecture }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64-linux
            runner: depot-ubuntu-24.04-8
            build_command: nix build -L .#binary-hoprd-x86_64-linux
          - architecture: aarch64-linux
            runner: depot-ubuntu-24.04-arm-8
            build_command: nix build -L .#binary-hoprd-aarch64-linux
    uses: hoprnet/hopr-workflows/.github/workflows/build-binaries.yaml@b063eebe2dfb2f92e7177a8f81383aaac4835d09 # build-binaries-v2
    permissions:
      contents: read
    with:
      source_branch: ${{ github.ref_name }}
      version_type: release
      architecture: ${{ matrix.architecture }}
      build_file: ./hoprd/Cargo.toml
      build_command: ${{ matrix.build_command }}
      binary: hoprd
      runner: ${{ matrix.runner }}
    secrets:
      gcp_service_account: ${{ secrets.GCP_SA_GITHUB_RUNNER }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_HOPRNET_PRIVATE_KEY }}
  build-docker:
    name: Docker
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker.yaml@024a130d36187da87c46820d738ca737b1a9e716 # build-docker-v2
    needs: build-binaries
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      source_branch: ${{ github.ref_name }}
      version_type: release
      build_matrix: >-
        [
          {
            "runner": "depot-ubuntu-24.04-4",
            "architecture": "x86_64-linux",
            "build_command": "nix build -L .#docker-hoprd-x86_64-linux"
          },
          {
            "runner": "depot-ubuntu-24.04-arm-4",
            "architecture": "aarch64-linux",
            "build_command": "nix build -L .#docker-hoprd-aarch64-linux"
          }
        ]
      build_file: ./hoprd/Cargo.toml
      docker_image_name: hoprd
      docker_image_format: skopeo
    secrets:
      gcp_service_account: ${{ secrets.GCP_SA_GITHUB_RUNNER }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
  release:
    name: Close release
    needs:
      - build-binaries
      - build-docker
    runs-on: depot-ubuntu-24.04
    permissions:
      contents: write
    outputs:
      released_version: ${{ steps.release_version.outputs.current_version }}
    steps:
      - name: Release version
        id: release_version
        uses: hoprnet/hopr-workflows/actions/release-version@53b6df9c98ee8a327d7533e76cd9aafcac6a1c2e # release-version-v4
        with:
          source_branch: ${{ github.ref_name }}
          file: ./hoprd/Cargo.toml
          release_type: ${{ inputs.release_type }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          zulip_api_key: ${{ secrets.ZULIP_API_KEY }}
          zulip_email: ${{ secrets.ZULIP_EMAIL }}
          zulip_channel: HOPRd
          zulip_topic: Releases
          gcp_service_account: ${{ secrets.GCP_SA_GITHUB_RUNNER }}
          gcp_artifact_package: hoprd
          github_token: ${{ secrets.GH_RUNNER_TOKEN }}
  post-release:
    name: Post Release
    runs-on: depot-ubuntu-24.04
    needs: release
    permissions:
      contents: read
    steps:
      - name: Bump dappnode testnet package
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.GNOSIS_GITHUB_WORKFLOW_TOKEN }}
          repository: dappnode/DAppNodePackage-Hopr-testnet
          event-type: bump
          client-payload: |-
            {
              "hoprd_version": "${{ needs.release.outputs.released_version }}"
            }
      - name: Deploy to Gnosis Staging
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.GNOSIS_GITHUB_WORKFLOW_TOKEN }}
          repository: gnosis/gnosis_vpn-infrastructure
          event-type: restart_hoprd
          client-payload: |-
            {
              "environment": "staging"
            }
